target 'HYHotPotForSwift' do

  use_frameworks!

  pod 'Alamofire'
  pod "PromiseKit"
  pod 'ElastosDIDSDK'
  pod 'QMUIKit'
  pod 'CYLTabBarController'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'SQLite.swift'
  pod 'RainbowSwift'
  pod 'IGListKit'
  
end
